# The services defined by the bundle.
services:
    zitec.flood_manager.manager:
        class: Zitec\FloodManagerBundle\Service\Manager
        arguments: ['@doctrine', '@logger', %zitec.flood_manager.manager.log_flood_attempts%]

    zitec.flood_manager.settings_generate_event_subscriber:
        class: Zitec\FloodManagerBundle\EventSubscriber\SettingsGenerateSubscriber
        tags:
            - { name: kernel.event_subscriber }

