services:
    zitec.flood_manager.form_extension.flood:
        class: Zitec\FloodManagerBundle\Form\Extension\FloodTypeExtension
        arguments:
            - '@zitec.flood_manager.manager'
            - '@translator.default'
            - '@request_stack'
        calls:
            - [setTimeInterval, ["@=service('zitec.settings.settings').get('flood_manager.default_time_interval')"]]
            - [setAttemptsNumber, ["@=service('zitec.settings.settings').get('flood_manager.default_attempts')"]]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }